Importing Libraries


In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Importin dataset

In [22]:
dataset = pd.read_excel('/content/housing.xlsx')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values
dataset.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
ocean_proximity         0
median_house_value      0
dtype: int64

In [23]:
print(x)

[[-122.23 37.88 41 ... 126 8.3252 'NEAR BAY']
 [-122.22 37.86 21 ... 1138 8.3014 'NEAR BAY']
 [-122.24 37.85 52 ... 177 7.2574 'NEAR BAY']
 ...
 [-121.22 39.43 17 ... 433 1.7 'INLAND']
 [-121.32 39.43 18 ... 349 1.8672 'INLAND']
 [-121.24 39.37 16 ... 530 2.3886 'INLAND']]


In [24]:
print(y)

[452600 358500 352100 ...  92300  84700  89400]


Taking care of missing data

In [25]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,0:8])
x[:,0:8]=imputer.transform(x[:,0:8])
print(x)

[[-122.23 37.88 41.0 ... 126.0 8.3252 'NEAR BAY']
 [-122.22 37.86 21.0 ... 1138.0 8.3014 'NEAR BAY']
 [-122.24 37.85 52.0 ... 177.0 7.2574 'NEAR BAY']
 ...
 [-121.22 39.43 17.0 ... 433.0 1.7 'INLAND']
 [-121.32 39.43 18.0 ... 349.0 1.8672 'INLAND']
 [-121.24 39.37 16.0 ... 530.0 2.3886 'INLAND']]


Encoding Categorical data

Encoding independent Variable

In [26]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [8])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [27]:
print(x)

[[0.0 0.0 0.0 ... 322.0 126.0 8.3252]
 [0.0 0.0 0.0 ... 2401.0 1138.0 8.3014]
 [0.0 0.0 0.0 ... 496.0 177.0 7.2574]
 ...
 [0.0 1.0 0.0 ... 1007.0 433.0 1.7]
 [0.0 1.0 0.0 ... 741.0 349.0 1.8672]
 [0.0 1.0 0.0 ... 1387.0 530.0 2.3886]]


Splitting the data into training set and test set

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=0)

In [29]:
print(x_train)

[[0.0 1.0 0.0 ... 228.0 65.0 4.2386]
 [0.0 0.0 0.0 ... 1485.0 447.0 4.3898]
 [1.0 0.0 0.0 ... 1022.0 368.0 3.9333]
 ...
 [0.0 0.0 0.0 ... 704.0 393.0 3.1977]
 [1.0 0.0 0.0 ... 1052.0 468.0 5.6315]
 [0.0 1.0 0.0 ... 1024.0 298.0 1.3882]]


In [31]:
print(y_train)

[500001 270000 196100 ... 289300 484600  69400]


In [32]:
print(x_test)

[[0.0 0.0 0.0 ... 1551.0 371.0 4.1518]
 [1.0 0.0 0.0 ... 1296.0 429.0 5.7796]
 [0.0 1.0 0.0 ... 1554.0 534.0 4.3487]
 ...
 [0.0 1.0 0.0 ... 850.0 326.0 3.2027]
 [0.0 1.0 0.0 ... 1072.0 374.0 6.1436]
 [1.0 0.0 0.0 ... 1462.0 406.0 3.3326]]


In [33]:
print(y_test)

[136900 241300 200700 ... 128600 259500 167600]


Feature Scaling

In [34]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [35]:
print(x_train)

[[-0.89150581  1.46934754 -0.01348032 ... -1.04760128 -1.1356496
   0.19001247]
 [-0.89150581 -0.68057418 -0.01348032 ...  0.05210918 -0.13688171
   0.26931072]
 [ 1.12169768 -0.68057418 -0.01348032 ... -0.35295521 -0.34343319
   0.02989505]
 ...
 [-0.89150581 -0.68057418 -0.01348032 ... -0.63116359 -0.27806879
  -0.35589721]
 [ 1.12169768 -0.68057418 -0.01348032 ... -0.32670914 -0.08197562
   0.92053182]
 [-0.89150581  1.46934754 -0.01348032 ... -0.35120548 -0.52645348
  -1.30490629]]


In [36]:
print(x_test)

[[-0.89150581 -0.68057418 -0.01348032 ...  0.10985054 -0.33558946
   0.14448941]
 [ 1.12169768 -0.68057418 -0.01348032 ... -0.11324108 -0.18394407
   0.99820424]
 [-0.89150581  1.46934754 -0.01348032 ...  0.11247515  0.09058637
   0.24775544]
 ...
 [-0.89150581  1.46934754 -0.01348032 ... -0.5034327  -0.45324536
  -0.35327491]
 [-0.89150581  1.46934754 -0.01348032 ... -0.30921176 -0.32774573
   1.18910742]
 [ 1.12169768 -0.68057418 -0.01348032 ...  0.03198719 -0.24407931
  -0.28514765]]


Training the Random forest Regression Model on the training set

In [37]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression
Rndm = RandomForestRegressor(max_depth=3, random_state=0).fit(x_train,y_train)
y_pred = Rndm.predict(x_test)



In [40]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
print(y_pred.shape)
print(y_test.shape)
print(Rndm.score(x_test,y_test))
mse = mean_squared_error(y_test, y_pred)
rmse = (mse**0.5)
print(mse)
print(rmse)

(4128,)
(4128,)
0.559365565441722
5745674310.709663
75800.2263236045
